[onprem_servers]
localhost ansible_connection=local

[onprem_servers:vars]
deployment_type=onprem

[gke_control]
localhost ansible_connection=local

[gke_control:vars]
deployment_type=k8s

[all:vars]
ansible_python_interpreter=/usr/bin/python3
